[package]
name = "rustcast"
version = "0.1.0"
authors = ["Shaun Campbell <shaun@shauntc.com>"]
edition = "2018"

[dependencies]
image = "0.23.*"
serde = "1.0.*"
serde_derive = "1.0.*"
serde_json = "1.0.57"