[package]
name = "rustcast"
version = "0.1.0"
authors = ["Shaun Campbell <shaun@shauntc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
serde = "1.0.103"
serde_derive = "1.0.103"